### request categories
GET http://localhost:3000/api/categories
Accept: : application/json
X-API-Key: RAHASIA
### create category

POST http://localhost:3000/api/categories HTTP/1.1
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
    "name": "gadget"
}

### update category
PUT http://localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
    "name": ""
}

### get categoryById
GET http://localhost:3000/api/categories/2
Accept: application/json
X-API-Key: RAHASIA

### dete category by id
DELETE http://localhost:3000/api/categories/1
Accept: application/json
X-API-Key: RAHASIA
